site_name: Event Invitations
repo_url: https://github.com/systopia/de.systopia.eventinvitation
site_description: 'Eine Anleitung für die Event-Invitation-Erweiterung.'
site_author: 'SYSTOPIA'
theme:
  name:
    material

nav:
  - Startseite: index.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - pymdownx.highlight:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

plugins:
  - search:
      lang: de
